export enum CacheKey {
    PlacedItems = "placed-items",
    PlacedItemTypes = "placed-item-types",
    Crops = "crops",
    Animals = "animals",
    Buildings = "buildings",
    Inventories = "inventories",
    InventoryTypes = "inventory-types",
    DailyRewards = "daily-rewards",
    User = "user",
    Tools = "tools",
    TutorialActive = "tutorial-active",
    SelectedTileId = "selected-tile-id",
    SelectedTileType = "selected-tile-type",
    SelectedTool = "selected-tool",
    DefaultInfo = "default-info",
    DeliveringProducts = "delivering-products",
    DeliveryIndex = "delivery-index",
    TutorialDepth = "tutorial-depth",
}