export const pathConstants = {
    default: "/",
    home: "/home",
    import: "/import",
    selectChain: "/select-chain",
    adjustTokens: "/adjust-tokens",
    assets: "/assets",
    settings: "/settings",
    play: "/play",
    partnerships: "/partnerships",
    partnershipsHoneycombProtocol: "/partnerships/honeycomb-protocol",
    partnershipsHoneycombProtocolHoneycombDailyReward: "/partnerships/honeycomb-protocol/honeycomb-daily-reward",
    partnershipsHoneycombProtocolHoneycombStaking: "/partnerships/honeycomb-protocol/honeycomb-staking",
    transfer: "/transfer",
}