export const pathConstants = {
    default: "/",
    home: "/home",
    import: "/import",
    importFromMnemonic: "/import/mnemonic",
    importFromPrivateKey: "/import/private-key",
    selectChain: "/select-chain",
    manageNFTCollections: "/manage-nft-collections",
    manageTokens: "/manage-tokens",
    assets: "/home/assets",
    settings: "/settings",
    play: "/play",
    partnerships: "/partnerships",
    partnershipsHoneycombProtocol: "/partnerships/honeycomb-protocol",
    partnershipsHoneycombProtocolHoneycombDailyReward: "/partnerships/honeycomb-protocol/honeycomb-daily-reward",
    partnershipsHoneycombProtocolHoneycombStaking: "/partnerships/honeycomb-protocol/honeycomb-staking",
    transfer: "/transfer",
    collection: "/collection",
    nft: "/nft",
    token: "/token",
    dapp: "/dapp",
    dappStarterShop: "/dapp/starter-shop",
    dappWholesaleMarket: "/dapp/wholesale-market",
}