/**
 * Constants for the CiFarm Wallet
 * This file defines all constants used throughout the application
 */
// =====================================
// DISCLOSURE CONSTANTS
// =====================================
export const PRIVATE_KEY_DISCLOSURE = "PRIVATE_KEY_DISCLOSURE"
export const MNEMONIC_DISCLOSURE = "MNEMONIC_DISCLOSURE"
export const WARNING_DISCLOSURE = "WARNING_DISCLOSURE"
export const WELCOME_DISCLOSURE = "WELCOME_DISCLOSURE"
export const SIGN_TRANSACTION_DISCLOSURE = "SIGN_TRANSACTION_DISCLOSURE"
export const MINT_DISCLOSURE = "MINT_DISCLOSURE"
export const GOLDS_DISCLOSURE = "GOLDS_DISCLOSURE"
export const PROFILE_DISCLOSURE = "PROFILE_DISCLOSURE"
export const INVITE_USER_DISCLOSURE = "INVITE_USER_DISCLOSURE"
export const MINT_AMOUNT_DISCLOSURE = "MINT_AMOUNT_DISCLOSURE"
export const NEIGHBORS_DISCLOSURE = "NEIGHBORS_DISCLOSURE"
export const NEIGHBORS_FILTER_DISCLOSURE = "NEIGHBORS_FILTER_DISCLOSURE"
export const QUESTS_DISCLOSURE = "QUESTS_DISCLOSURE"
export const ROADSIDE_STAND_DISCLOSURE = "ROADSIDE_STAND_DISCLOSURE"
export const SELECT_TOKEN_DISCLOSURE = "SELECT_TOKEN_DISCLOSURE"
export const SHOP_DISCLOSURE = "SHOP_DISCLOSURE"
export const INVENTORY_DISCLOSURE = "INVENTORY_DISCLOSURE"
export const SELECT_NFT_DISCLOSURE = "SELECT_NFT_DISCLOSURE"
export const SELECT_NFT_COLLECTION_DISCLOSURE = "SELECT_NFT_COLLECTION_DISCLOSURE"
export const CONVERT_NFT_DISCLOSURE = "CONVERT_NFT_DISCLOSURE"
export const NFTS_CLAIMED_DISCLOSURE = "NFTS_CLAIMED_DISCLOSURE"
export const TRANSFER_NFT_DISCLOSURE = "TRANSFER_NFT_DISCLOSURE"
export const TRANSFER_TOKEN_DISCLOSURE = "TRANSFER_TOKEN_DISCLOSURE"
export const INFO_DISCLOSURE = "INFO_DISCLOSURE"
export const NFT_STORAGE_DISCLOSURE = "NFT_STORAGE_DISCLOSURE"
export const DOWNLOAD_DISCLOSURE = "DOWNLOAD_DISCLOSURE"
export const SETTINGS_DISCLOSURE = "SETTINGS_DISCLOSURE"
export const DOWNLOADING_DISCLOSURE = "DOWNLOADING_DISCLOSURE"
export const SELECT_INVENTORY_DISCLOSURE = "SELECT_INVENTORY_DISCLOSURE"
export const SELL_DISCLOSURE = "SELL_DISCLOSURE"
export const UPGRADE_DISCLOSURE = "UPGRADE_DISCLOSURE"
export const SHIP_DISCLOSURE = "SHIP_DISCLOSURE"
export const DAILY_DISCLOSURE = "DAILY_DISCLOSURE"
export const BUY_GOLDS_DISCLOSURE = "BUY_GOLDS_DISCLOSURE"
export const BUY_ENERGY_DISCLOSURE = "BUY_ENERGY_DISCLOSURE"
export const NOTIFICATION_DISCLOSURE = "NOTIFICATION_DISCLOSURE"
export const CONNECT_DISCLOSURE = "CONNECT_DISCLOSURE"
export const REFERRAL_DISCLOSURE = "REFERRAL_DISCLOSURE"
export const SHEET_TOKEN_DISCLOSURE = "SHEET_TOKEN_DISCLOSURE"
export const SHEET_WHOLSALE_MARKET_DISCLOSURE = "SHEET_WHOLSALE_MARKET_DISCLOSURE"
export const SHEET_TRANSFER_TOKEN_DISCLOSURE = "SHEET_TRANSFER_TOKEN_DISCLOSURE"
export const SHEET_NFT_DISCLOSURE = "SHEET_NFT_DISCLOSURE"
export const SHEET_GAME_ITEM_DISCLOSURE = "SHEET_GAME_ITEM_DISCLOSURE"
export const SHEET_BOTTOM_NAV_DISCLOSURE = "SHEET_BOTTOM_NAV_DISCLOSURE"
export const AUTHENTICATING_DISCLOSURE = "AUTHENTICATING_DISCLOSURE"
export const PURCHASE_NFT_BOXES_DISCLOSURE = "PURCHASE_NFT_BOXES_DISCLOSURE"
export const FIREBASE_AUTH_SWR_MUTATION = "FIREBASE_AUTH_SWR_MUTATION"
export const SELECT_CHAIN_DISCLOSURE = "SELECT_CHAIN_DISCLOSURE"
export const PURCHASE_NFT_BOX_SWR_MUTATION = "PURCHASE_NFT_BOX_SWR_MUTATION"

// =====================================
// FORM HOOK CONSTANTS
// =====================================
// React Hook Form constants
export const MINT_OFFCHAIN_TOKENS_RHF = "MINT_OFFCHAIN_TOKENS_RHF"
export const TRANSFER_TOKEN_RHF = "TRANSFER_TOKEN_RHF"
// Formik constants
export const TRANSFER_TOKEN_FORMIK = "TRANSFER_TOKEN_FORMIK"
export const IMPORT_ACCOUNT_FORMIK = "IMPORT_ACCOUNT_FORMIK"
export const TRANSFER_NFT_FORMIK = "TRANSFER_NFT_FORMIK"
export const PURCHASE_NFT_BOXES_FORMIK = "PURCHASE_NFT_BOXES_FORMIK"

// =====================================
// SWR CONSTANTS
// =====================================
export const NATIVE_COINGEKCO_SWR = "NATIVE_COINGEKCO_SWR"

// =====================================
// GRAPHQL MUTATION CONSTANTS
// =====================================

// Auth & User mutations
export const GRAPHQL_MUTATION_UPDATE_TUTORIAL_SWR_MUTATION = "GRAPHQL_MUTATION_UPDATE_TUTORIAL_SWR_MUTATION"
export const GRAPHQL_MUTATION_UPDATE_REFERRAL_SWR_MUTATION = "GRAPHQL_MUTATION_UPDATE_REFERRAL_SWR_MUTATION"
export const GRAPHQL_MUTATION_UPDATE_FOLLOW_X_SWR_MUTATION = "GRAPHQL_MUTATION_UPDATE_FOLLOW_X_SWR_MUTATION"
export const GRAPHQL_MUTATION_UPDATE_PROFILE_SWR_MUTATION = "GRAPHQL_MUTATION_UPDATE_PROFILE_SWR_MUTATION"
export const GRAPHQL_MUTATION_WRAP_SOLANA_METAPLEX_SWR_MUTATION = "GRAPHQL_MUTATION_WRAP_SOLANA_METAPLEX_SWR_MUTATION"

// Reward mutations
export const GRAPHQL_MUTATION_CLAIM_DAILY_REWARD_SWR_MUTATION = "GRAPHQL_MUTATION_CLAIM_DAILY_REWARD_SWR_MUTATION"
export const GRAPHQL_MUTATION_CLAIM_HONEYCOMB_DAILY_REWARD_SWR_MUTATION = "GRAPHQL_MUTATION_CLAIM_HONEYCOMB_DAILY_REWARD_SWR_MUTATION"
export const GRAPHQL_MUTATION_MINT_OFFCHAIN_TOKENS_SWR_MUTATION = "GRAPHQL_MUTATION_MINT_OFFCHAIN_TOKENS_SWR_MUTATION"
export const GRAPHQL_MUTATION_SPIN_SWR_MUTATION = "GRAPHQL_MUTATION_SPIN_SWR_MUTATION"
export const GRAPHQL_MUTATION_SEND_PURCHASE_SOLANA_NFT_BOXES_TRANSACTION_SWR_MUTATION = "GRAPHQL_MUTATION_SEND_PURCHASE_SOLANA_NFT_BOXES_TRANSACTION_SWR_MUTATION"
export const GRAPHQL_MUTATION_CREATE_PURCHASE_SOLANA_NFT_BOXES_TRANSACTION_SWR_MUTATION = "GRAPHQL_MUTATION_CREATE_PURCHASE_SOLANA_NFT_BOXES_TRANSACTION_SWR_MUTATION"
export const GRAPHQL_MUTATION_CREATE_BUY_GOLDS_SOLANA_TRANSACTION_SWR_MUTATION = "GRAPHQL_MUTATION_CREATE_BUY_GOLDS_SOLANA_TRANSACTION_SWR_MUTATION"
export const GRAPHQL_MUTATION_SEND_BUY_GOLDS_SOLANA_TRANSACTION_SWR_MUTATION = "GRAPHQL_MUTATION_SEND_BUY_GOLDS_SOLANA_TRANSACTION_SWR_MUTATION"
export const GRAPHQL_MUTATION_CREATE_CONVERT_SOLANA_METAPLEX_NFTS_TRANSACTION_SWR_MUTATION = "GRAPHQL_MUTATION_CREATE_CONVERT_SOLANA_METAPLEX_NFTS_TRANSACTION_SWR_MUTATION"
export const GRAPHQL_MUTATION_SEND_CONVERT_SOLANA_METAPLEX_NFTS_TRANSACTION_SWR_MUTATION = "GRAPHQL_MUTATION_SEND_CONVERT_SOLANA_METAPLEX_NFTS_TRANSACTION_SWR_MUTATION"
export const GRAPHQL_MUTATION_CREATE_BUY_ENERGY_SOLANA_TRANSACTION_SWR_MUTATION = "GRAPHQL_MUTATION_CREATE_BUY_ENERGY_SOLANA_TRANSACTION_SWR_MUTATION"
export const GRAPHQL_MUTATION_SEND_BUY_ENERGY_SOLANA_TRANSACTION_SWR_MUTATION = "GRAPHQL_MUTATION_SEND_BUY_ENERGY_SOLANA_TRANSACTION_SWR_MUTATION"
// Animal related mutations
export const GRAPHQL_MUTATION_HARVEST_ANIMAL_SWR_MUTATION = "GRAPHQL_MUTATION_HARVEST_ANIMAL_SWR_MUTATION"
export const GRAPHQL_MUTATION_BUY_ANIMAL_SWR_MUTATION = "GRAPHQL_MUTATION_BUY_ANIMAL_SWR_MUTATION"
export const GRAPHQL_MUTATION_THIEF_ANIMAL_SWR_MUTATION = "GRAPHQL_MUTATION_THIEF_ANIMAL_SWR_MUTATION"
export const GRAPHQL_MUTATION_HELP_USE_ANIMAL_MEDICINE_SWR_MUTATION = "GRAPHQL_MUTATION_HELP_USE_ANIMAL_MEDICINE_SWR_MUTATION"
export const GRAPHQL_MUTATION_USE_ANIMAL_MEDICINE_SWR_MUTATION = "GRAPHQL_MUTATION_USE_ANIMAL_MEDICINE_SWR_MUTATION"
export const GRAPHQL_MUTATION_USE_ANIMAL_FEED_SWR_MUTATION = "GRAPHQL_MUTATION_USE_ANIMAL_FEED_SWR_MUTATION"
export const GRAPHQL_MUTATION_HELP_USE_ANIMAL_FEED_SWR_MUTATION = "GRAPHQL_MUTATION_HELP_USE_ANIMAL_FEED_SWR_MUTATION"

// Plant related mutations
export const GRAPHQL_MUTATION_HARVEST_PLANT_SWR_MUTATION = "GRAPHQL_MUTATION_HARVEST_PLANT_SWR_MUTATION"
export const GRAPHQL_MUTATION_PLANT_SEED_SWR_MUTATION = "GRAPHQL_MUTATION_PLANT_SEED_SWR_MUTATION"
export const GRAPHQL_MUTATION_USE_WATERING_CAN_SWR_MUTATION = "GRAPHQL_MUTATION_USE_WATERING_CAN_SWR_MUTATION"
export const GRAPHQL_MUTATION_HELP_USE_WATERING_CAN_SWR_MUTATION = "GRAPHQL_MUTATION_HELP_USE_WATERING_CAN_SWR_MUTATION"
export const GRAPHQL_MUTATION_THIEF_PLANT_SWR_MUTATION = "GRAPHQL_MUTATION_THIEF_PLANT_SWR_MUTATION"
// Fruit related mutations
export const GRAPHQL_MUTATION_HARVEST_FRUIT_SWR_MUTATION = "GRAPHQL_MUTATION_HARVEST_FRUIT_SWR_MUTATION"
export const GRAPHQL_MUTATION_THIEF_FRUIT_SWR_MUTATION = "GRAPHQL_MUTATION_THIEF_FRUIT_SWR_MUTATION"
export const GRAPHQL_MUTATION_USE_FRUIT_FERTILIZER_SWR_MUTATION = "GRAPHQL_MUTATION_USE_FRUIT_FERTILIZER_SWR_MUTATION"
export const GRAPHQL_MUTATION_HELP_USE_FRUIT_FERTILIZER_SWR_MUTATION = "GRAPHQL_MUTATION_HELP_USE_FRUIT_FERTILIZER_SWR_MUTATION"
export const GRAPHQL_MUTATION_BUY_FRUIT_SWR_MUTATION = "GRAPHQL_MUTATION_BUY_FRUIT_SWR_MUTATION"

// Tool & supply related mutations
export const GRAPHQL_MUTATION_USE_BUG_NET_SWR_MUTATION = "GRAPHQL_MUTATION_USE_BUG_NET_SWR_MUTATION"
export const GRAPHQL_MUTATION_HELP_USE_BUG_NET_SWR_MUTATION = "GRAPHQL_MUTATION_HELP_USE_BUG_NET_SWR_MUTATION"
export const GRAPHQL_MUTATION_USE_FERTILIZER_SWR_MUTATION = "GRAPHQL_MUTATION_USE_FERTILIZER_SWR_MUTATION"
export const GRAPHQL_MUTATION_USE_HERBICIDE_SWR_MUTATION = "GRAPHQL_MUTATION_USE_HERBICIDE_SWR_MUTATION"
export const GRAPHQL_MUTATION_HELP_USE_HERBICIDE_SWR_MUTATION = "GRAPHQL_MUTATION_HELP_USE_HERBICIDE_SWR_MUTATION"
export const GRAPHQL_MUTATION_USE_PESTICIDE_SWR_MUTATION = "GRAPHQL_MUTATION_USE_PESTICIDE_SWR_MUTATION"
export const GRAPHQL_MUTATION_HELP_USE_PESTICIDE_SWR_MUTATION = "GRAPHQL_MUTATION_HELP_USE_PESTICIDE_SWR_MUTATION"
export const GRAPHQL_MUTATION_BUY_TOOL_SWR_MUTATION = "GRAPHQL_MUTATION_BUY_TOOL_SWR_MUTATION"
export const GRAPHQL_MUTATION_BUY_SUPPLIES_SWR_MUTATION = "GRAPHQL_MUTATION_BUY_SUPPLIES_SWR_MUTATION"
export const GRAPHQL_MUTATION_BUY_CROP_SEEDS_SWR_MUTATION = "GRAPHQL_MUTATION_BUY_CROP_SEEDS_SWR_MUTATION"
export const GRAPHQL_MUTATION_BUY_FLOWER_SEEDS_SWR_MUTATION = "GRAPHQL_MUTATION_BUY_FLOWER_SEEDS_SWR_MUTATION"

// Building related mutations
export const GRAPHQL_MUTATION_UPGRADE_BUILDING_SWR_MUTATION = "GRAPHQL_MUTATION_UPGRADE_BUILDING_SWR_MUTATION"
export const GRAPHQL_MUTATION_BUY_BUILDING_SWR_MUTATION = "GRAPHQL_MUTATION_BUY_BUILDING_SWR_MUTATION"
export const GRAPHQL_MUTATION_BUY_TILE_SWR_MUTATION = "GRAPHQL_MUTATION_BUY_TILE_SWR_MUTATION"

// Inventory related mutations
export const GRAPHQL_MUTATION_UPDATE_INVENTORY_INDEX_SWR_MUTATION = "GRAPHQL_MUTATION_UPDATE_INVENTORY_INDEX_SWR_MUTATION"
export const GRAPHQL_MUTATION_MOVE_INVENTORY_SWR_MUTATION = "GRAPHQL_MUTATION_MOVE_INVENTORY_SWR_MUTATION"
export const GRAPHQL_MUTATION_MOVE_SWR_MUTATION = "GRAPHQL_MUTATION_MOVE_SWR_MUTATION"

// Product related mutations
export const GRAPHQL_MUTATION_DELIVER_PRODUCT_SWR_MUTATION = "GRAPHQL_MUTATION_DELIVER_PRODUCT_SWR_MUTATION"
export const GRAPHQL_MUTATION_DELIVER_MORE_PRODUCT_SWR_MUTATION = "GRAPHQL_MUTATION_DELIVER_MORE_PRODUCT_SWR_MUTATION"
export const GRAPHQL_MUTATION_RETAIN_PRODUCT_SWR_MUTATION = "GRAPHQL_MUTATION_RETAIN_PRODUCT_SWR_MUTATION"
export const GRAPHQL_MUTATION_SELL_SWR_MUTATION = "GRAPHQL_MUTATION_SELL_SWR_MUTATION"


export const GRAPHQL_MUTATION_AUTHENTICATION_SWR_MUTATION = "GRAPHQL_MUTATION_AUTHENTICATION_SWR_MUTATION"
export const GRAPHQL_MUTATION_FREEZE_SOLANA_METAPLEX_NFT_SWR_MUTATION = "GRAPHQL_MUTATION_FREEZE_SOLANA_METAPLEX_NFT_SWR_MUTATION"
export const GRAPHQL_MUTATION_VALIDATE_SOLANA_METAPLEX_NFT_FROZEN_SWR_MUTATION = "GRAPHQL_MUTATION_VALIDATE_SOLANA_METAPLEX_NFT_FROZEN_SWR_MUTATION"
export const GRAPHQL_MUTATION_PURCHASE_SOLANA_NFT_STARTER_BOX_SWR_MUTATION = "GRAPHQL_MUTATION_PURCHASE_SOLANA_NFT_STARTER_BOX_SWR_MUTATION"
export const GRAPHQL_MUTATION_CREATE_SHIP_SOLANA_TRANSACTION_SWR_MUTATION = "GRAPHQL_MUTATION_CREATE_SHIP_SOLANA_TRANSACTION_SWR_MUTATION"
export const GRAPHQL_MUTATION_SEND_SHIP_SOLANA_TRANSACTION_SWR_MUTATION = "GRAPHQL_MUTATION_SEND_SHIP_SOLANA_TRANSACTION_SWR_MUTATION"
export const GRAPHQL_MUTATION_CREATE_WRAP_SOLANA_METAPLEX_NFT_TRANSACTION_SWR_MUTATION = "GRAPHQL_MUTATION_CREATE_WRAP_SOLANA_METAPLEX_NFT_TRANSACTION_SWR_MUTATION"
export const GRAPHQL_MUTATION_SEND_WRAP_SOLANA_METAPLEX_NFT_TRANSACTION_SWR_MUTATION = "GRAPHQL_MUTATION_SEND_WRAP_SOLANA_METAPLEX_NFT_TRANSACTION_SWR_MUTATION"
export const GRAPHQL_MUTATION_CREATE_UNWRAP_SOLANA_METAPLEX_NFT_TRANSACTION_SWR_MUTATION = "GRAPHQL_MUTATION_CREATE_UNWRAP_SOLANA_METAPLEX_NFT_TRANSACTION_SWR_MUTATION"
export const GRAPHQL_MUTATION_SEND_UNWRAP_SOLANA_METAPLEX_NFT_TRANSACTION_SWR_MUTATION = "GRAPHQL_MUTATION_SEND_UNWRAP_SOLANA_METAPLEX_NFT_TRANSACTION_SWR_MUTATION"
export const GRAPHQL_MUTATION_CREATE_PURCHASE_SUI_NFT_BOXES_TRANSACTION_SWR_MUTATION = "GRAPHQL_MUTATION_CREATE_PURCHASE_SUI_NFT_BOXES_TRANSACTION_SWR_MUTATION"
export const GRAPHQL_MUTATION_REFRESH_SWR_MUTATION = "GRAPHQL_MUTATION_REFRESH_SWR_MUTATION"

// Social related mutations
export const GRAPHQL_MUTATION_FOLLOW_SWR_MUTATION = "GRAPHQL_MUTATION_FOLLOW_SWR_MUTATION"
export const GRAPHQL_MUTATION_UNFOLLOW_SWR_MUTATION = "GRAPHQL_MUTATION_UNFOLLOW_SWR_MUTATION"
export const GRAPHQL_MUTATION_VISIT_SWR_MUTATION = "GRAPHQL_MUTATION_VISIT_SWR_MUTATION"
export const GRAPHQL_MUTATION_RETURN_SWR_MUTATION = "GRAPHQL_MUTATION_RETURN_SWR_MUTATION"

// =====================================
// GRAPHQL QUERY CONSTANTS
// =====================================
export const GRAPHQL_QUERY_NEIGHBORS_SWR = "GRAPHQL_QUERY_NEIGHBORS_SWR"
export const GRAPHQL_QUERY_FOLLOWEES_SWR = "GRAPHQL_QUERY_FOLLOWEES_SWR"
export const GRAPHQL_QUERY_USER_SWR = "GRAPHQL_QUERY_USER_SWR"
export const GRAPHQL_QUERY_USER_SWR_MUTATION = "GRAPHQL_QUERY_USER_SWR_MUTATION"
export const GRAPHQL_QUERY_STATIC_SWR = "GRAPHQL_QUERY_STATIC_SWR"
export const GRAPHQL_QUERY_PLACED_ITEMS_SWR_MUTATION = "GRAPHQL_QUERY_PLACED_ITEMS_SWR_MUTATION"
export const GRAPHQL_QUERY_INVENTORIES_SWR = "GRAPHQL_QUERY_INVENTORIES_SWR"
export const GRAPHQL_QUERY_STORED_PLACED_ITEMS_SWR = "GRAPHQL_QUERY_STORED_PLACED_ITEMS_SWR"
export const GRAPHQL_QUERY_NFTS_VALIDATED_SWR_MUTATION = "GRAPHQL_QUERY_NFTS_VALIDATED_SWR_MUTATION"
export const GRAPHQL_QUERY_VAULT_CURRENT_SWR = "GRAPHQL_QUERY_VAULT_CURRENT_SWR"

// =====================================
// SPECIAL PURPOSE HOOKS
// =====================================
export const HONEYCOMB_SEND_TRANSACTION_SWR_MUTATION = "HONEYCOMB_SEND_TRANSACTION_SWR_MUTATION"
export const HONEYCOMB_SEND_TRANSACTIONS_SWR_MUTATION = "HONEYCOMB_SEND_TRANSACTIONS_SWR_MUTATION"
export const SEND_UMI_SERIALIZED_TX_SWR_MUTATION = "SEND_UMI_SERIALIZED_TX_SWR_MUTATION"

export const SIGN_UMI_SERIALIZED_TX_SWR_MUTATION = "SIGN_UMI_SERIALIZED_TX_SWR_MUTATION"
export const SIGN_UMI_SERIALIZED_TXS_SWR_MUTATION = "SIGN_UMI_SERIALIZED_TXS_SWR_MUTATION"
export const TRANSFER_TOKEN_SWR_MUTATION = "TRANSFER_TOKEN_SWR_MUTATION"
export const TRANSFER_NFT_SWR_MUTATION = "TRANSFER_NFT_SWR_MUTATION"
export const SIGN_SOLANA_TRANSACTION_SWR_MUTATION = "SIGN_SOLANA_TRANSACTION_SWR_MUTATION"
export const SIGN_SUI_TRANSACTION_SWR_MUTATION = "SIGN_SUI_TRANSACTION_SWR_MUTATION"

// =====================================
// IO CONSTANTS
// =====================================
export const WS = "WS"

// =====================================
// ASSET URL CONSTANTS
// =====================================
export const EXPERIENCE_IMAGE_URL = "/assets/ui/common/experience.png"
export const TOKEN_IMAGE_URL = "/assets/ui/common/icon-carrot.png"
export const GOLD_IMAGE_URL = "/assets/ui/common/icon-gold.png"
export const CHECK_IMAGE_URL = "/assets/ui/common/check.png"

// =====================================
// BACKWARD COMPATIBILITY CONSTANTS
// =====================================

// For backward compatibility (QUERY_ -> GRAPHQL_QUERY_)
export const QUERY_USER_SWR_MUTATION = GRAPHQL_QUERY_USER_SWR
export const QUERY_STATIC_SWR_MUTATION = GRAPHQL_QUERY_STATIC_SWR
export const QUERY_INVENTORIES_SWR_MUTATION = GRAPHQL_QUERY_INVENTORIES_SWR
export const QUERY_NEIGHBORS_SWR_MUTATION = GRAPHQL_QUERY_NEIGHBORS_SWR
export const QUERY_FOLLOWEES_SWR_MUTATION = GRAPHQL_QUERY_FOLLOWEES_SWR
export const QUERY_PLACED_ITEMS_SWR_MUTATION = GRAPHQL_QUERY_PLACED_ITEMS_SWR_MUTATION

// For backward compatibility (QUERY_GRAPHQL_ -> GRAPHQL_QUERY_)
export const QUERY_GRAPHQL_USER_SWR_MUTATION = GRAPHQL_QUERY_USER_SWR
export const QUERY_GRAPHQL_STATIC_SWR_MUTATION = GRAPHQL_QUERY_STATIC_SWR
export const QUERY_GRAPHQL_INVENTORIES_SWR_MUTATION = GRAPHQL_QUERY_INVENTORIES_SWR
export const QUERY_GRAPHQL_NEIGHBORS_SWR_MUTATION = GRAPHQL_QUERY_NEIGHBORS_SWR
export const QUERY_GRAPHQL_FOLLOWEES_SWR_MUTATION = GRAPHQL_QUERY_FOLLOWEES_SWR
export const QUERY_GRAPHQL_PLACED_ITEMS_SWR_MUTATION = GRAPHQL_QUERY_PLACED_ITEMS_SWR_MUTATION

// =====================================
// MODAL CONSTANTS
// =====================================
export const SELL_MODAL = "SELL_MODAL"
export const PURCHASE_NFT_BOXES_MODAL = "PURCHASE_NFT_BOXES_MODAL"