export const CREATE_PIN_FORM = "CREATE_PIN_FORM"
export const ENTER_PIN_FORM = "ENTER_PIN_FORM"
export const NATIVE_COINGEKCO_SWR = "NATIVE_COINGEKCO_SWR"

//disclosure
export const PRIVATE_KEY_DISCLOSURE = "PRIVATE_KEY_DISCLOSURE"
export const MNEMONIC_DISCLOSURE = "MNEMONIC_DISCLOSURE"
export const WARNING_DISCLOSURE = "WARNING_DISCLOSURE"