export const CREATE_PIN_FORM = "CREATE_PIN_FORM"
export const ENTER_PIN_FORM = "ENTER_PIN_FORM"

//disclosure
export const PRIVATE_KEY_DISCLOSURE = "PRIVATE_KEY_DISCLOSURE"
export const MNEMONIC_DISCLOSURE = "MNEMONIC_DISCLOSURE"
export const WARNING_DISCLOSURE = "WARNING_DISCLOSURE"

//swr
export const NATIVE_COINGEKCO_SWR = "NATIVE_COINGEKCO_SWR"

//swr mutations
export const API_AUTHENTICATION_SWR_MUTATION = "API_AUTHENTICATION_SWR_MUTATION"
export const QUERY_USER_SWR = "QUERY_USER_SWR"
export const QUERY_STATIC_SWR = "QUERY_STATIC_SWR"
export const QUERY_INVENTORIES_SWR = "QUERY_INVENTORIES_SWR"

//io
export const GAMEPLAY_IO = "GAMEPLAY_IO"