import {
    useNativeCoinGeckoSWR,
    useGraphQLMutationMintOffchainTokensSwrMutation,
    useWs,
    useTransferTokenFormik,
    useTransferTokenSwrMutation,
    useHoneycombSendTransactionSwrMutation,
    useGraphQLMutationUnfollowSwrMutation,
    useGraphQLMutationFollowSwrMutation,
    useGraphQLMutationClaimHoneycombDailyRewardSwrMutation,
    useGraphQLQueryInventoriesSwr,
    useGraphQLQueryStaticSwr,
    useGraphQLQueryFolloweesSwr,
    useGraphQLQueryNeighborsSwr,
    useGraphQLQueryUserSwr,
    useGraphQLQueryPlacedItemsSwrMutation,
    useGraphQLMutationUpdateFollowXSwrMutation,
    useTransferNFTFormik,
    useTransferNFTSwrMutation,
    useGraphQLMutationWrapSolanaMetaplexSwrMutation,
    useHoneycombSendTransactionsSwrMutation,
    useGraphQLQueryStoredPlacedItemsSwr,
    useGraphQLMutationCreateShipSolanaTransactionSwrMutation,
    useGraphQLMutationSendShipSolanaTransactionSwrMutation,
    useGraphQLMutationCreateWrapSolanaMetaplexNFTTransactionSwrMutation,
    useGraphQLMutationSendUnwrapSolanaMetaplexNFTTransactionSwrMutation,
    useGraphQLMutationSendWrapSolanaMetaplexNFTTransactionSwrMutation,
    useGraphQLMutationCreateUnwrapSolanaMetaplexNFTTransactionSwrMutation,
    useGraphQLMutationCreateBuyGoldsSolanaTransactionSwrMutation,
    useGraphQLMutationSendBuyGoldsSolanaTransactionSwrMutation,
    useGraphQLQueryVaultCurrentSwr,
    useSignSolanaTransactionTxSwrMutation,
    useSignSuiTransactionTxSwrMutation,
    useGraphQLMutationRefreshSwrMutation,
    useGraphQLMutationLogoutSwrMutation,
    useGraphQLMutationCreatePurchaseSolanaNFTBoxesTransactionSwrMutation,
    useGraphQLMutationSendPurchaseSolanaNFTBoxesTransactionSwrMutation,
    usePurchaseNFTBoxesFormik,
    useGraphQLMutationCreatePurchaseSuiNFTBoxesTransactionSwrMutation,
    useGraphQLQueryUserSwrMutation,
    useGraphQLMutationSendConvertSolanaMetaplexNFTsTransactionSwrMutation,
    useGraphQLMutationCreateConvertSolanaMetaplexNFTsTransactionSwrMutation,
    useGraphQLMutationCreateBuyEnergySolanaTransactionSwrMutation,
    useGraphQLMutationSendBuyEnergySolanaTransactionSwrMutation,
    useGraphQLMutationCreateExpandLandLimitSolanaTransactionSwrMutation,
    useGraphQLMutationSendExpandLandLimitSolanaTransactionSwrMutation,
    useGraphQLQueryOccupiedPlacedItemCounts,
    useGraphQLQueryBulkPaidsSwr,
    useGraphQLQueryLeaderboardSwr,
} from "@/hooks"
import {
    SingletonHookProvider as BaseSingletonHookProvider,
    SingletonHook2Provider as BaseSingletonHook2Provider,
} from "@/modules/singleton-hook"
import { useDisclosure } from "react-use-disclosure"
import React, { PropsWithChildren } from "react"
import { useGraphQLMutationUpdateReferralSwrMutation } from "@/hooks"

export const SingletonHookProvider = ({ children }: PropsWithChildren) => (
    <BaseSingletonHookProvider
        hooks={{
            // disclosures
            NATIVE_COINGEKCO_SWR: useNativeCoinGeckoSWR(),
            PRIVATE_KEY_DISCLOSURE: useDisclosure(),
            MNEMONIC_DISCLOSURE: useDisclosure(),
            WARNING_DISCLOSURE: useDisclosure(),
            TUTORIAL_DISCLOSURE: useDisclosure(),
            SIGN_TRANSACTION_DISCLOSURE: useDisclosure(),
            NEIGHBORS_DISCLOSURE: useDisclosure(),
            NEIGHBORS_FILTER_DISCLOSURE: useDisclosure(),
            QUESTS_DISCLOSURE: useDisclosure(),
            NOTIFICATION_DISCLOSURE: useDisclosure(),
            PROFILE_DISCLOSURE: useDisclosure(),
            MINT_DISCLOSURE: useDisclosure(),
            SELECT_CHAIN_DISCLOSURE: useDisclosure(),
            CONVERT_NFT_DISCLOSURE: useDisclosure(),
            MINT_AMOUNT_DISCLOSURE: useDisclosure(),
            WALLET_CONNECTION_REQUIRED_DISCLOSURE: useDisclosure(),
            NFT_DISCLOSURE: useDisclosure(),
            TOKEN_DISCLOSURE: useDisclosure(),
            INFO_DISCLOSURE: useDisclosure(),
            EXPAND_LAND_LIMIT_DISCLOSURE: useDisclosure(),
            NFT_STORAGE_DISCLOSURE: useDisclosure(),
            DOWNLOAD_DISCLOSURE: useDisclosure(),
            DOWNLOADING_DISCLOSURE: useDisclosure(),
            SHOP_DISCLOSURE: useDisclosure(),
            SELECT_NFT_COLLECTION_DISCLOSURE: useDisclosure(),
            INVENTORY_DISCLOSURE: useDisclosure(),
            ROADSIDE_STAND_DISCLOSURE: useDisclosure(),
            TRANSFER_TOKEN_DISCLOSURE: useDisclosure(),
            TRANSFER_NFT_DISCLOSURE: useDisclosure(),
            SELECT_INVENTORY_DISCLOSURE: useDisclosure(),
            SETTINGS_DISCLOSURE: useDisclosure(),
            UPGRADE_DISCLOSURE: useDisclosure(),
            SELL_DISCLOSURE: useDisclosure(),
            DAILY_DISCLOSURE: useDisclosure(),
            SHIP_DISCLOSURE: useDisclosure(),
            NFTS_CLAIMED_DISCLOSURE: useDisclosure(),
            CONNECT_DISCLOSURE: useDisclosure(),
            WELCOME_DISCLOSURE: useDisclosure(),
            BUY_GOLDS_DISCLOSURE: useDisclosure(),
            BUY_ENERGY_DISCLOSURE: useDisclosure(),
            SHEET_TOKEN_DISCLOSURE: useDisclosure(),
            SHEET_TRANSFER_TOKEN_DISCLOSURE: useDisclosure(),
            SHEET_NFT_DISCLOSURE: useDisclosure(),
            SHEET_GAME_ITEM_DISCLOSURE: useDisclosure(),
            SHEET_BOTTOM_NAV_DISCLOSURE: useDisclosure(),
            SHEET_WHOLSALE_MARKET_BULK_DISCLOSURE: useDisclosure(),
            PURCHASE_NFT_BOXES_DISCLOSURE: useDisclosure(),
            REFERRAL_DISCLOSURE: useDisclosure(),
            AUTHENTICATING_DISCLOSURE: useDisclosure(),
            GRAPHQL_MUTATION_MINT_OFFCHAIN_TOKENS_SWR_MUTATION: useGraphQLMutationMintOffchainTokensSwrMutation(),
            GRAPHQL_MUTATION_UNFOLLOW_SWR_MUTATION: useGraphQLMutationUnfollowSwrMutation(),
            GRAPHQL_MUTATION_FOLLOW_SWR_MUTATION: useGraphQLMutationFollowSwrMutation(),
            GRAPHQL_MUTATION_CLAIM_HONEYCOMB_DAILY_REWARD_SWR_MUTATION: useGraphQLMutationClaimHoneycombDailyRewardSwrMutation(),
            GRAPHQL_MUTATION_UPDATE_FOLLOW_X_SWR_MUTATION: useGraphQLMutationUpdateFollowXSwrMutation(),
            GRAPHQL_MUTATION_UPDATE_REFERRAL_SWR_MUTATION: useGraphQLMutationUpdateReferralSwrMutation(),
            GRAPHQL_MUTATION_LOGOUT_SWR_MUTATION: useGraphQLMutationLogoutSwrMutation(),
            GRAPHQL_MUTATION_WRAP_SOLANA_METAPLEX_SWR_MUTATION: useGraphQLMutationWrapSolanaMetaplexSwrMutation(),
            SIGN_SOLANA_TRANSACTION_SWR_MUTATION: useSignSolanaTransactionTxSwrMutation(),
            SIGN_SUI_TRANSACTION_SWR_MUTATION: useSignSuiTransactionTxSwrMutation(),
            GRAPHQL_MUTATION_SEND_PURCHASE_SOLANA_NFT_BOXES_TRANSACTION_SWR_MUTATION: useGraphQLMutationSendPurchaseSolanaNFTBoxesTransactionSwrMutation(),
            GRAPHQL_MUTATION_CREATE_PURCHASE_SOLANA_NFT_BOXES_TRANSACTION_SWR_MUTATION: useGraphQLMutationCreatePurchaseSolanaNFTBoxesTransactionSwrMutation(),
            GRAPHQL_MUTATION_CREATE_SHIP_SOLANA_TRANSACTION_SWR_MUTATION: useGraphQLMutationCreateShipSolanaTransactionSwrMutation(),
            GRAPHQL_MUTATION_SEND_SHIP_SOLANA_TRANSACTION_SWR_MUTATION: useGraphQLMutationSendShipSolanaTransactionSwrMutation(),
            GRAPHQL_MUTATION_CREATE_WRAP_SOLANA_METAPLEX_NFT_TRANSACTION_SWR_MUTATION: useGraphQLMutationCreateWrapSolanaMetaplexNFTTransactionSwrMutation(),
            GRAPHQL_MUTATION_SEND_WRAP_SOLANA_METAPLEX_NFT_TRANSACTION_SWR_MUTATION: useGraphQLMutationSendWrapSolanaMetaplexNFTTransactionSwrMutation(),
            GRAPHQL_MUTATION_CREATE_UNWRAP_SOLANA_METAPLEX_NFT_TRANSACTION_SWR_MUTATION: useGraphQLMutationCreateUnwrapSolanaMetaplexNFTTransactionSwrMutation(),
            GRAPHQL_MUTATION_SEND_UNWRAP_SOLANA_METAPLEX_NFT_TRANSACTION_SWR_MUTATION: useGraphQLMutationSendUnwrapSolanaMetaplexNFTTransactionSwrMutation(),           
            GRAPHQL_MUTATION_CREATE_BUY_GOLDS_SOLANA_TRANSACTION_SWR_MUTATION: useGraphQLMutationCreateBuyGoldsSolanaTransactionSwrMutation(),
            GRAPHQL_MUTATION_SEND_BUY_GOLDS_SOLANA_TRANSACTION_SWR_MUTATION: useGraphQLMutationSendBuyGoldsSolanaTransactionSwrMutation(),
            GRAPHQL_MUTATION_CREATE_BUY_ENERGY_SOLANA_TRANSACTION_SWR_MUTATION: useGraphQLMutationCreateBuyEnergySolanaTransactionSwrMutation(),
            GRAPHQL_MUTATION_SEND_BUY_ENERGY_SOLANA_TRANSACTION_SWR_MUTATION: useGraphQLMutationSendBuyEnergySolanaTransactionSwrMutation(),
            GRAPHQL_MUTATION_REFRESH_SWR_MUTATION: useGraphQLMutationRefreshSwrMutation(),
            GRAPHQL_MUTATION_CREATE_PURCHASE_SUI_NFT_BOXES_TRANSACTION_SWR_MUTATION: useGraphQLMutationCreatePurchaseSuiNFTBoxesTransactionSwrMutation(),
            GRAPHQL_MUTATION_CREATE_CONVERT_SOLANA_METAPLEX_NFTS_TRANSACTION_SWR_MUTATION: useGraphQLMutationCreateConvertSolanaMetaplexNFTsTransactionSwrMutation(),
            GRAPHQL_MUTATION_SEND_CONVERT_SOLANA_METAPLEX_NFTS_TRANSACTION_SWR_MUTATION: useGraphQLMutationSendConvertSolanaMetaplexNFTsTransactionSwrMutation(), 
            GRAPHQL_MUTATION_CREATE_EXPAND_LAND_LIMIT_SOLANA_TRANSACTION_SWR_MUTATION: useGraphQLMutationCreateExpandLandLimitSolanaTransactionSwrMutation(),
            GRAPHQL_MUTATION_SEND_EXPAND_LAND_LIMIT_SOLANA_TRANSACTION_SWR_MUTATION: useGraphQLMutationSendExpandLandLimitSolanaTransactionSwrMutation(),
            // honeycomb
            HONEYCOMB_SEND_TRANSACTION_SWR_MUTATION: useHoneycombSendTransactionSwrMutation(),  
            HONEYCOMB_SEND_TRANSACTIONS_SWR_MUTATION: useHoneycombSendTransactionsSwrMutation(),
            // queries
            GRAPHQL_QUERY_INVENTORIES_SWR: useGraphQLQueryInventoriesSwr(),
            GRAPHQL_QUERY_STATIC_SWR: useGraphQLQueryStaticSwr(),
            GRAPHQL_QUERY_FOLLOWEES_SWR: useGraphQLQueryFolloweesSwr(),
            GRAPHQL_QUERY_NEIGHBORS_SWR: useGraphQLQueryNeighborsSwr(),
            GRAPHQL_QUERY_USER_SWR: useGraphQLQueryUserSwr(),
            GRAPHQL_QUERY_PLACED_ITEMS_SWR_MUTATION: useGraphQLQueryPlacedItemsSwrMutation(),        
            GRAPHQL_QUERY_STORED_PLACED_ITEMS_SWR: useGraphQLQueryStoredPlacedItemsSwr(),
            GRAPHQL_QUERY_VAULT_CURRENT_SWR: useGraphQLQueryVaultCurrentSwr(),
            GRAPHQL_QUERY_OCCUPIED_PLACED_ITEM_COUNTS_SWR: useGraphQLQueryOccupiedPlacedItemCounts(),
            GRAPHQL_QUERY_USER_SWR_MUTATION: useGraphQLQueryUserSwrMutation(),
            GRAPHQL_QUERY_BULK_PAIDS_SWR: useGraphQLQueryBulkPaidsSwr(),
            GRAPHQL_QUERY_LEADERBOARD_SWR: useGraphQLQueryLeaderboardSwr(),
            // Using new constants with GraphQL mutations
            //io

            WS: useWs(),
        }}
    >
        {children}
    </BaseSingletonHookProvider>
)

export const SingletonHook2Provider = ({ children }: PropsWithChildren) => (
    <BaseSingletonHook2Provider
        hooks={{
            TRANSFER_TOKEN_FORMIK: useTransferTokenFormik(),
            // IMPORT_ACCOUNT_FORMIK: useImportAccountFormik(),
            TRANSFER_NFT_FORMIK: useTransferNFTFormik(),
            TRANSFER_TOKEN_SWR_MUTATION: useTransferTokenSwrMutation(), 
            // transfer token
            TRANSFER_NFT_SWR_MUTATION: useTransferNFTSwrMutation(),
            PURCHASE_NFT_BOXES_FORMIK: usePurchaseNFTBoxesFormik(),
        }}
    >
        {children}
    </BaseSingletonHook2Provider>
)