import {
    useGraphQLMutationMintOffchainTokensSwrMutation,
    useWs,
    useGraphQLMutationUnfollowSwrMutation,
    useGraphQLMutationFollowSwrMutation,
    useGraphQLMutationClaimHoneycombDailyRewardSwrMutation,
    useGraphQLQueryInventoriesSwr,
    useGraphQLQueryStaticSwr,
    useGraphQLQueryFolloweesSwr,
    useGraphQLQueryNeighborsSwr,
    useGraphQLQueryUserSwr,
    useGraphQLQueryPlacedItemsSwrMutation,
    useGraphQLMutationUpdateFollowXSwrMutation,
    useGraphQLMutationWrapSolanaMetaplexSwrMutation,
    useGraphQLQueryStoredPlacedItemsSwr,
    useGraphQLMutationCreateShipSolanaTransactionSwrMutation,
    useGraphQLMutationSendShipSolanaTransactionSwrMutation,
    useGraphQLMutationCreateWrapSolanaMetaplexNFTTransactionSwrMutation,
    useGraphQLMutationSendUnwrapSolanaMetaplexNFTTransactionSwrMutation,
    useGraphQLMutationSendWrapSolanaMetaplexNFTTransactionSwrMutation,
    useGraphQLMutationCreateUnwrapSolanaMetaplexNFTTransactionSwrMutation,
    useGraphQLMutationCreateBuyGoldsSolanaTransactionSwrMutation,
    useGraphQLMutationSendBuyGoldsSolanaTransactionSwrMutation,
    useGraphQLQueryVaultCurrentSwr,
    useSignSolanaTransactionTxSwrMutation,
    useSignSuiTransactionTxSwrMutation,
    useGraphQLMutationRefreshSwrMutation,
    useGraphQLMutationLogoutSwrMutation,
    useGraphQLMutationCreatePurchaseSolanaNFTBoxesTransactionSwrMutation,
    useGraphQLMutationSendPurchaseSolanaNFTBoxesTransactionSwrMutation,
    useGraphQLMutationCreatePurchaseSuiNFTBoxesTransactionSwrMutation,
    useGraphQLQueryUserSwrMutation,
    useGraphQLMutationSendConvertSolanaMetaplexNFTsTransactionSwrMutation,
    useGraphQLMutationCreateConvertSolanaMetaplexNFTsTransactionSwrMutation,
    useGraphQLMutationCreateBuyEnergySolanaTransactionSwrMutation,
    useGraphQLMutationSendBuyEnergySolanaTransactionSwrMutation,
    useGraphQLMutationCreateExpandLandLimitSolanaTransactionSwrMutation,
    useGraphQLMutationSendExpandLandLimitSolanaTransactionSwrMutation,
    useGraphQLQueryOccupiedPlacedItemCounts,
    useGraphQLQueryBulkPaidsSwr,
    useGraphQLQueryLeaderboardSwr,
    useGraphQLMutationUpdateReferralSwrMutation,
} from "../../hooks"
import {
    BaseSingletonHookProvider,
} from "../../core"
import { useDisclosure } from "react-use-disclosure"
import React, { PropsWithChildren } from "react"
import {
    GRAPHQL_MUTATION_SEND_WRAP_SOLANA_METAPLEX_NFT_TRANSACTION_SWR_MUTATION,
    GRAPHQL_MUTATION_SEND_BUY_ENERGY_SOLANA_TRANSACTION_SWR_MUTATION,
    GRAPHQL_MUTATION_CREATE_PURCHASE_SUI_NFT_BOXES_TRANSACTION_SWR_MUTATION,
    GRAPHQL_MUTATION_CREATE_CONVERT_SOLANA_METAPLEX_NFTS_TRANSACTION_SWR_MUTATION,
    GRAPHQL_MUTATION_CREATE_BUY_ENERGY_SOLANA_TRANSACTION_SWR_MUTATION,
    GRAPHQL_MUTATION_SEND_BUY_GOLDS_SOLANA_TRANSACTION_SWR_MUTATION,
    GRAPHQL_MUTATION_CREATE_BUY_GOLDS_SOLANA_TRANSACTION_SWR_MUTATION,
    GRAPHQL_MUTATION_SEND_CONVERT_SOLANA_METAPLEX_NFTS_TRANSACTION_SWR_MUTATION,
    GRAPHQL_QUERY_LEADERBOARD_SWR,
    GRAPHQL_QUERY_BULK_PAIDS_SWR,
    GRAPHQL_QUERY_USER_SWR_MUTATION,
    GRAPHQL_QUERY_STORED_PLACED_ITEMS_SWR,
    GRAPHQL_MUTATION_CLAIM_HONEYCOMB_DAILY_REWARD_SWR_MUTATION,
    GRAPHQL_MUTATION_CREATE_EXPAND_LAND_LIMIT_SOLANA_TRANSACTION_SWR_MUTATION,
    GRAPHQL_MUTATION_CREATE_PURCHASE_SOLANA_NFT_BOXES_TRANSACTION_SWR_MUTATION,
    GRAPHQL_MUTATION_CREATE_SHIP_SOLANA_TRANSACTION_SWR_MUTATION,
    GRAPHQL_MUTATION_CREATE_UNWRAP_SOLANA_METAPLEX_NFT_TRANSACTION_SWR_MUTATION,
    GRAPHQL_MUTATION_CREATE_WRAP_SOLANA_METAPLEX_NFT_TRANSACTION_SWR_MUTATION,
    GRAPHQL_MUTATION_FOLLOW_SWR_MUTATION,
    GRAPHQL_MUTATION_MINT_OFFCHAIN_TOKENS_SWR_MUTATION,
    GRAPHQL_MUTATION_REFRESH_SWR_MUTATION,
    GRAPHQL_MUTATION_SEND_EXPAND_LAND_LIMIT_SOLANA_TRANSACTION_SWR_MUTATION,
    GRAPHQL_MUTATION_SEND_PURCHASE_SOLANA_NFT_BOXES_TRANSACTION_SWR_MUTATION,
    GRAPHQL_MUTATION_SEND_SHIP_SOLANA_TRANSACTION_SWR_MUTATION,
    GRAPHQL_MUTATION_SEND_UNWRAP_SOLANA_METAPLEX_NFT_TRANSACTION_SWR_MUTATION,
    GRAPHQL_MUTATION_UNFOLLOW_SWR_MUTATION,
    GRAPHQL_MUTATION_UPDATE_FOLLOW_X_SWR_MUTATION,
    GRAPHQL_MUTATION_UPDATE_REFERRAL_SWR_MUTATION,
    GRAPHQL_MUTATION_WRAP_SOLANA_METAPLEX_SWR_MUTATION,
    GRAPHQL_QUERY_FOLLOWEES_SWR,
    GRAPHQL_QUERY_INVENTORIES_SWR,
    GRAPHQL_QUERY_NEIGHBORS_SWR,
    GRAPHQL_QUERY_OCCUPIED_PLACED_ITEM_COUNTS_SWR,
    GRAPHQL_QUERY_PLACED_ITEMS_SWR_MUTATION,
    GRAPHQL_QUERY_STATIC_SWR,
    GRAPHQL_QUERY_USER_SWR,
    GRAPHQL_QUERY_VAULT_CURRENT_SWR,
    INVENTORY_MODAL_DISCLOSURE,
    MINT_AMOUNT_MODAL_DISCLOSURE,
    MINT_MODAL_DISCLOSURE,
    NFTS_CLAIMED_MODAL_DISCLOSURE,
    PURCHASE_NFT_BOXES_MODAL_DISCLOSURE,
    REFERRAL_MODAL_DISCLOSURE,
    ROADSIDE_STAND_MODAL_DISCLOSURE,
    SELECT_INVENTORY_MODAL_DISCLOSURE,
    SELECT_NFT_COLLECTION_MODAL_DISCLOSURE,
    SELL_MODAL_DISCLOSURE,
    SETTINGS_MODAL_DISCLOSURE,
    SHIP_MODAL_DISCLOSURE,
    SHOP_MODAL_DISCLOSURE,
    SIGN_SOLANA_TRANSACTION_SWR_MUTATION,
    SIGN_SUI_TRANSACTION_SWR_MUTATION,
    TRANSFER_NFT_MODAL_DISCLOSURE,
    TRANSFER_TOKEN_MODAL_DISCLOSURE,
    UPGRADE_MODAL_DISCLOSURE,
    WALLET_CONNECTION_REQUIRED_MODAL_DISCLOSURE,
    WELCOME_MODAL_DISCLOSURE,
    GRAPHQL_MUTATION_LOGOUT_SWR_MUTATION,
    DAILY_MODAL_DISCLOSURE,
    CONNECT_MODAL_DISCLOSURE,
    BUY_GOLDS_MODAL_DISCLOSURE,
    TOKEN_SHEET_DISCLOSURE,
    NFT_SHEET_DISCLOSURE,
    BOTTOM_NAV_SHEET_DISCLOSURE,
    WHOLSALE_MARKET_BULK_SHEET_DISCLOSURE,
    GAME_ITEM_SHEET_DISCLOSURE,
    CONVERT_NFT_MODAL_DISCLOSURE,
    INFO_MODAL_DISCLOSURE,
    NFT_STORAGE_MODAL_DISCLOSURE,
    EXPAND_LAND_LIMIT_MODAL_DISCLOSURE,
    DOWNLOAD_MODAL_DISCLOSURE,
    AUTHENTICATING_MODAL_DISCLOSURE,
    BUY_ENERGY_MODAL_DISCLOSURE,
    WARNING_MODAL_DISCLOSURE,
    TUTORIAL_MODAL_DISCLOSURE,
    SIGN_TRANSACTION_MODAL_DISCLOSURE,
    NEIGHBORS_MODAL_DISCLOSURE,
    NEIGHBORS_FILTER_MODAL_DISCLOSURE,
    QUESTS_MODAL_DISCLOSURE,
    NOTIFICATION_MODAL_DISCLOSURE,
    PROFILE_MODAL_DISCLOSURE,
    DOWNLOADING_MODAL_DISCLOSURE,
    WS,
    TRANSACTION_SUBMITTING_MOBILE_MODAL_DISCLOSURE,
} from "../../keys"

export const SingletonHookProvider = ({ children }: PropsWithChildren) => (
    <BaseSingletonHookProvider
        hooks={{
            // disclosures
            [WARNING_MODAL_DISCLOSURE]: useDisclosure(),
            [TUTORIAL_MODAL_DISCLOSURE]: useDisclosure(),
            [SIGN_TRANSACTION_MODAL_DISCLOSURE]: useDisclosure(),
            [NEIGHBORS_MODAL_DISCLOSURE]: useDisclosure(),
            [NEIGHBORS_FILTER_MODAL_DISCLOSURE]: useDisclosure(),
            [QUESTS_MODAL_DISCLOSURE]: useDisclosure(),
            [NOTIFICATION_MODAL_DISCLOSURE]: useDisclosure(),
            [PROFILE_MODAL_DISCLOSURE]: useDisclosure(),
            [MINT_MODAL_DISCLOSURE]: useDisclosure(),
            [CONVERT_NFT_MODAL_DISCLOSURE]: useDisclosure(),
            [MINT_AMOUNT_MODAL_DISCLOSURE]: useDisclosure(),
            [WALLET_CONNECTION_REQUIRED_MODAL_DISCLOSURE]: useDisclosure(),
            [INFO_MODAL_DISCLOSURE]: useDisclosure(),
            [EXPAND_LAND_LIMIT_MODAL_DISCLOSURE]: useDisclosure(),
            [NFT_STORAGE_MODAL_DISCLOSURE]: useDisclosure(),
            [DOWNLOAD_MODAL_DISCLOSURE]: useDisclosure(),
            [DOWNLOADING_MODAL_DISCLOSURE]: useDisclosure(),
            [SHOP_MODAL_DISCLOSURE]: useDisclosure(),
            [SELECT_NFT_COLLECTION_MODAL_DISCLOSURE]: useDisclosure(),
            [INVENTORY_MODAL_DISCLOSURE]: useDisclosure(),
            [ROADSIDE_STAND_MODAL_DISCLOSURE]: useDisclosure(),
            [TRANSFER_TOKEN_MODAL_DISCLOSURE]: useDisclosure(),
            [TRANSFER_NFT_MODAL_DISCLOSURE]: useDisclosure(),
            [SELECT_INVENTORY_MODAL_DISCLOSURE]: useDisclosure(),
            [SETTINGS_MODAL_DISCLOSURE]: useDisclosure(),
            [UPGRADE_MODAL_DISCLOSURE]: useDisclosure(),
            [SELL_MODAL_DISCLOSURE]: useDisclosure(),
            [DAILY_MODAL_DISCLOSURE]: useDisclosure(),
            [SHIP_MODAL_DISCLOSURE]: useDisclosure(),
            [NFTS_CLAIMED_MODAL_DISCLOSURE]: useDisclosure(),
            [CONNECT_MODAL_DISCLOSURE]: useDisclosure(),
            [WELCOME_MODAL_DISCLOSURE]: useDisclosure(),
            [BUY_GOLDS_MODAL_DISCLOSURE]: useDisclosure(),
            [BUY_ENERGY_MODAL_DISCLOSURE]: useDisclosure(),
            [TOKEN_SHEET_DISCLOSURE]: useDisclosure(),
            [NFT_SHEET_DISCLOSURE]: useDisclosure(),
            [GAME_ITEM_SHEET_DISCLOSURE]: useDisclosure(),
            [BOTTOM_NAV_SHEET_DISCLOSURE]: useDisclosure(),
            [WHOLSALE_MARKET_BULK_SHEET_DISCLOSURE]: useDisclosure(),
            [PURCHASE_NFT_BOXES_MODAL_DISCLOSURE]: useDisclosure(),
            [REFERRAL_MODAL_DISCLOSURE]: useDisclosure(),
            [AUTHENTICATING_MODAL_DISCLOSURE]: useDisclosure(),
            [TRANSACTION_SUBMITTING_MOBILE_MODAL_DISCLOSURE]: useDisclosure(),
            [GRAPHQL_MUTATION_MINT_OFFCHAIN_TOKENS_SWR_MUTATION]: useGraphQLMutationMintOffchainTokensSwrMutation(),
            [GRAPHQL_MUTATION_UNFOLLOW_SWR_MUTATION]: useGraphQLMutationUnfollowSwrMutation(),
            [GRAPHQL_MUTATION_FOLLOW_SWR_MUTATION]: useGraphQLMutationFollowSwrMutation(),
            [GRAPHQL_MUTATION_CLAIM_HONEYCOMB_DAILY_REWARD_SWR_MUTATION]: useGraphQLMutationClaimHoneycombDailyRewardSwrMutation(),
            [GRAPHQL_MUTATION_UPDATE_FOLLOW_X_SWR_MUTATION]: useGraphQLMutationUpdateFollowXSwrMutation(),
            [GRAPHQL_MUTATION_UPDATE_REFERRAL_SWR_MUTATION]: useGraphQLMutationUpdateReferralSwrMutation(),
            [GRAPHQL_MUTATION_LOGOUT_SWR_MUTATION]: useGraphQLMutationLogoutSwrMutation(),
            [GRAPHQL_MUTATION_WRAP_SOLANA_METAPLEX_SWR_MUTATION]: useGraphQLMutationWrapSolanaMetaplexSwrMutation(),
            [SIGN_SOLANA_TRANSACTION_SWR_MUTATION]: useSignSolanaTransactionTxSwrMutation(),
            [SIGN_SUI_TRANSACTION_SWR_MUTATION]: useSignSuiTransactionTxSwrMutation(),
            [GRAPHQL_MUTATION_SEND_PURCHASE_SOLANA_NFT_BOXES_TRANSACTION_SWR_MUTATION]: useGraphQLMutationSendPurchaseSolanaNFTBoxesTransactionSwrMutation(),
            [GRAPHQL_MUTATION_CREATE_PURCHASE_SOLANA_NFT_BOXES_TRANSACTION_SWR_MUTATION]: useGraphQLMutationCreatePurchaseSolanaNFTBoxesTransactionSwrMutation(),
            [GRAPHQL_MUTATION_CREATE_SHIP_SOLANA_TRANSACTION_SWR_MUTATION]: useGraphQLMutationCreateShipSolanaTransactionSwrMutation(),
            [GRAPHQL_MUTATION_SEND_SHIP_SOLANA_TRANSACTION_SWR_MUTATION]: useGraphQLMutationSendShipSolanaTransactionSwrMutation(),
            [GRAPHQL_MUTATION_CREATE_WRAP_SOLANA_METAPLEX_NFT_TRANSACTION_SWR_MUTATION]: useGraphQLMutationCreateWrapSolanaMetaplexNFTTransactionSwrMutation(),
            [GRAPHQL_MUTATION_SEND_WRAP_SOLANA_METAPLEX_NFT_TRANSACTION_SWR_MUTATION]: useGraphQLMutationSendWrapSolanaMetaplexNFTTransactionSwrMutation(),
            [GRAPHQL_MUTATION_CREATE_UNWRAP_SOLANA_METAPLEX_NFT_TRANSACTION_SWR_MUTATION]: useGraphQLMutationCreateUnwrapSolanaMetaplexNFTTransactionSwrMutation(),
            [GRAPHQL_MUTATION_SEND_UNWRAP_SOLANA_METAPLEX_NFT_TRANSACTION_SWR_MUTATION]: useGraphQLMutationSendUnwrapSolanaMetaplexNFTTransactionSwrMutation(),           
            [GRAPHQL_MUTATION_CREATE_BUY_GOLDS_SOLANA_TRANSACTION_SWR_MUTATION]: useGraphQLMutationCreateBuyGoldsSolanaTransactionSwrMutation(),
            [GRAPHQL_MUTATION_SEND_BUY_GOLDS_SOLANA_TRANSACTION_SWR_MUTATION]: useGraphQLMutationSendBuyGoldsSolanaTransactionSwrMutation(),
            [GRAPHQL_MUTATION_CREATE_BUY_ENERGY_SOLANA_TRANSACTION_SWR_MUTATION]: useGraphQLMutationCreateBuyEnergySolanaTransactionSwrMutation(),
            [GRAPHQL_MUTATION_SEND_BUY_ENERGY_SOLANA_TRANSACTION_SWR_MUTATION]: useGraphQLMutationSendBuyEnergySolanaTransactionSwrMutation(),
            [GRAPHQL_MUTATION_REFRESH_SWR_MUTATION]: useGraphQLMutationRefreshSwrMutation(),
            [GRAPHQL_MUTATION_CREATE_PURCHASE_SUI_NFT_BOXES_TRANSACTION_SWR_MUTATION]: useGraphQLMutationCreatePurchaseSuiNFTBoxesTransactionSwrMutation(),
            [GRAPHQL_MUTATION_CREATE_CONVERT_SOLANA_METAPLEX_NFTS_TRANSACTION_SWR_MUTATION]: useGraphQLMutationCreateConvertSolanaMetaplexNFTsTransactionSwrMutation(),
            [GRAPHQL_MUTATION_SEND_CONVERT_SOLANA_METAPLEX_NFTS_TRANSACTION_SWR_MUTATION]: useGraphQLMutationSendConvertSolanaMetaplexNFTsTransactionSwrMutation(),
            [GRAPHQL_MUTATION_CREATE_EXPAND_LAND_LIMIT_SOLANA_TRANSACTION_SWR_MUTATION]: useGraphQLMutationCreateExpandLandLimitSolanaTransactionSwrMutation(),
            [GRAPHQL_MUTATION_SEND_EXPAND_LAND_LIMIT_SOLANA_TRANSACTION_SWR_MUTATION]: useGraphQLMutationSendExpandLandLimitSolanaTransactionSwrMutation(),
            // queries
            [GRAPHQL_QUERY_INVENTORIES_SWR]: useGraphQLQueryInventoriesSwr(),
            [GRAPHQL_QUERY_STATIC_SWR]: useGraphQLQueryStaticSwr(),
            [GRAPHQL_QUERY_FOLLOWEES_SWR]: useGraphQLQueryFolloweesSwr(),
            [GRAPHQL_QUERY_NEIGHBORS_SWR]: useGraphQLQueryNeighborsSwr(),
            [GRAPHQL_QUERY_USER_SWR]: useGraphQLQueryUserSwr(),
            [GRAPHQL_QUERY_PLACED_ITEMS_SWR_MUTATION]: useGraphQLQueryPlacedItemsSwrMutation(),        
            [GRAPHQL_QUERY_STORED_PLACED_ITEMS_SWR]: useGraphQLQueryStoredPlacedItemsSwr(),
            [GRAPHQL_QUERY_VAULT_CURRENT_SWR]: useGraphQLQueryVaultCurrentSwr(),
            [GRAPHQL_QUERY_OCCUPIED_PLACED_ITEM_COUNTS_SWR]: useGraphQLQueryOccupiedPlacedItemCounts(),
            [GRAPHQL_QUERY_USER_SWR_MUTATION]: useGraphQLQueryUserSwrMutation(),
            [GRAPHQL_QUERY_BULK_PAIDS_SWR]: useGraphQLQueryBulkPaidsSwr(),
            [GRAPHQL_QUERY_LEADERBOARD_SWR]: useGraphQLQueryLeaderboardSwr(),
            // Using new constants with GraphQL mutations
            //io    
            [WS]: useWs(),
        }}
    >
        {children}
    </BaseSingletonHookProvider>
)