// blockchain singleton hook keys, use to retrieve blockchain data
export const TRANSFER_TOKEN_SWR_MUTATION = "TRANSFER_TOKEN_SWR_MUTATION"
export const TRANSFER_NFT_SWR_MUTATION = "TRANSFER_NFT_SWR_MUTATION"
export const SIGN_SOLANA_TRANSACTION_SWR_MUTATION = "SIGN_SOLANA_TRANSACTION_SWR_MUTATION"
export const SIGN_SUI_TRANSACTION_SWR_MUTATION = "SIGN_SUI_TRANSACTION_SWR_MUTATION"